<?php

namespace Database\Seeders;

use App\Models\JobOpening;
use Illuminate\Database\Seeder;

class JobOpeningSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'id' => 10,
                'position' => 'Project Manager',
                'description' => 'Lowongan untuk frontend developer dengan pengalaman React 1-3 tahun. Bekerja remote/hybrid.',
                'industry' => 'Teknologi',
                'company' => 'TPL SV IPB',
                'type' => 'job',
                'deadline' => '2026-03-16 06:59:00',
                'location' => 'Bogor',
                'image' => 'storage/job_openings/udB4J8J5ciMy1nurTY2BvZqIlF1g8uHmInaS6Uvx.jpg',
                'salary_min' => 5000000,
                'salary_max' => 10000000,
                'requirements' => ['mahir', 'jago'],
                'link' => 'https://id.jobstreet.com/id/career-advice/article/contoh-surat-lamaran-kerja-yang-baik-dan-benar',
                'active' => true,
                'created_by_id' => 22,
                'created_by_type' => 'alumni',
                'approved_by_id' => 3,
                'approved_at' => '2026-02-17 18:33:54',
                'created_at' => '2026-02-14 03:55:16',
                'updated_at' => '2026-02-17 18:33:54',
            ],
            [
                'id' => 8,
                'position' => 'staff admin',
                'description' => 'Lowongan untuk staff admin dengan pengalaman React 1-3 tahun. Bekerja remote/hybrid.',
                'industry' => 'Perikanan',
                'company' => 'Kementrian Perikanan',
                'type' => 'job',
                'deadline' => '2026-04-15 23:59:00',
                'location' => 'Bogor',
                'image' => null,
                'salary_min' => 5000000,
                'salary_max' => 10000000,
                'requirements' => ['ganteng', 'gondrong'],
                'link' => 'https://id.jobstreet.com/id/career-advice/article/contoh-surat-lamaran-kerja-yang-baik-dan-benar',
                'active' => true,
                'created_by_id' => 3,
                'created_by_type' => 'admin',
                'approved_by_id' => 3,
                'approved_at' => '2026-02-14 02:39:01',
                'created_at' => '2026-02-14 02:39:01',
                'updated_at' => '2026-02-14 02:39:01',
            ],
            [
                'id' => 7,
                'position' => 'staff admin',
                'description' => 'Lowongan untuk staff admin dengan pengalaman React 1-3 tahun. Bekerja remote/hybrid.',
                'industry' => 'Perikanan',
                'company' => 'Kementrian Perikanan',
                'type' => 'job',
                'deadline' => '2026-04-15 23:59:00',
                'location' => 'Bogor',
                'image' => 'storage/job_openings/cVEch3a7KobI0XGfg5S1pbjZXS4dXrEYdLSV0trv.png',
                'salary_min' => 5000000,
                'salary_max' => 10000000,
                'requirements' => ['ganteng', 'gondrong'],
                'link' => 'https://id.jobstreet.com/id/career-advice/article/contoh-surat-lamaran-kerja-yang-baik-dan-benar',
                'active' => true,
                'created_by_id' => 3,
                'created_by_type' => 'admin',
                'approved_by_id' => 3,
                'approved_at' => '2026-02-14 02:37:51',
                'created_at' => '2026-02-14 02:37:53',
                'updated_at' => '2026-02-14 02:37:53',
            ],
            [
                'id' => 6,
                'position' => 'staff admin',
                'description' => 'Lowongan untuk staff admin dengan pengalaman React 1-3 tahun. Bekerja remote/hybrid.',
                'industry' => 'Perikanan',
                'company' => 'Kementrian Perikanan',
                'type' => 'internship',
                'deadline' => '2026-04-15 23:59:00',
                'location' => 'Bogor',
                'image' => 'storage/job_openings/UoBz8lVkXmhzpQ9ldNNrDfLRhXgO7KjvXTapPgi9.png',
                'salary_min' => 5000000,
                'salary_max' => 10000000,
                'requirements' => ['ganteng', 'gondrong'],
                'link' => 'https://id.jobstreet.com/id/career-advice/article/contoh-surat-lamaran-kerja-yang-baik-dan-benar',
                'active' => true,
                'created_by_id' => 3,
                'created_by_type' => 'admin',
                'approved_by_id' => 3,
                'approved_at' => '2026-02-10 08:40:51',
                'created_at' => '2026-02-10 08:40:51',
                'updated_at' => '2026-02-10 08:40:51',
            ],
            [
                'id' => 5,
                'position' => 'staff admin',
                'description' => 'Lowongan untuk staff admin dengan pengalaman React 1-3 tahun. Bekerja remote/hybrid.',
                'industry' => 'Perikanan',
                'company' => 'Kementrian Perikanan',
                'type' => 'internship',
                'deadline' => '2026-04-15 23:59:00',
                'location' => 'Bogor',
                'image' => 'storage/job_openings/EVO430OXbG3PdRqgnus3Ui4v3WfZPRYhEegpwhBq.png',
                'salary_min' => 5000000,
                'salary_max' => 10000000,
                'requirements' => ['ganteng', 'gondrong'],
                'link' => 'https://id.jobstreet.com/id/career-advice/article/contoh-surat-lamaran-kerja-yang-baik-dan-benar',
                'active' => true,
                'created_by_id' => 3,
                'created_by_type' => 'admin',
                'approved_by_id' => 3,
                'approved_at' => '2026-02-10 08:40:31',
                'created_at' => '2026-02-10 08:40:31',
                'updated_at' => '2026-02-10 08:40:31',
            ],
            [
                'id' => 4,
                'position' => 'marketing',
                'description' => 'Lowongan untuk marketing dengan pengalaman React 1-3 tahun. Bekerja remote/hybrid.',
                'industry' => 'Perkebunan',
                'company' => 'microsoft',
                'type' => 'job',
                'deadline' => '2026-03-15 23:59:00',
                'location' => 'Jakarta',
                'image' => 'storage/job_openings/CpqfPKgdeZjiel9LjtBOQVBanxiGeOgrNrN5EK9g.png',
                'salary_min' => 5000000,
                'salary_max' => 10000000,
                'requirements' => ['ganteng', 'gondrong'],
                'link' => 'https://id.jobstreet.com/id/career-advice/article/contoh-surat-lamaran-kerja-yang-baik-dan-benar',
                'active' => true,
                'created_by_id' => 3,
                'created_by_type' => 'admin',
                'approved_by_id' => 3,
                'approved_at' => '2026-02-10 08:39:02',
                'created_at' => '2026-02-10 08:39:03',
                'updated_at' => '2026-02-10 08:39:03',
            ],
            [
                'id' => 3,
                'position' => 'Frontend Dev',
                'description' => 'Lowongan untuk frontend developer dengan pengalaman React 1-3 tahun. Bekerja remote/hybrid.',
                'industry' => 'Teknologi',
                'company' => 'microsoft',
                'type' => 'job',
                'deadline' => '2026-03-15 23:59:00',
                'location' => 'Jakarta',
                'image' => 'storage/job_openings/uVs7rhygtZJKoBSUT6ZpkbiwZE0Y1KMLI1LLyE7w.png',
                'salary_min' => 5000000,
                'salary_max' => 10000000,
                'requirements' => ['mahir', 'jago'],
                'link' => 'https://id.jobstreet.com/id/career-advice/article/contoh-surat-lamaran-kerja-yang-baik-dan-benar',
                'active' => true,
                'created_by_id' => 3,
                'created_by_type' => 'admin',
                'approved_by_id' => 3,
                'approved_at' => '2026-02-09 13:08:13',
                'created_at' => '2026-02-09 13:08:14',
                'updated_at' => '2026-02-09 13:08:14',
            ],
        ];

        foreach ($data as $item) {
            JobOpening::updateOrCreate(
                ['id' => $item['id']],
                $item
            );
        }
    }
}

